rancher/rke2-docs

docs/install/network_options.md

Update Network options documentations.

Update network options docs

---

docs/security/policies.md

Signed-off-by: Brad Davidson <brad.davidson@rancher.com>

Remove managedFields from sample netpols

---

docs/known_issues.md

https://github.com/rancher/rke2/issues/2518
https://github.com/rancher/rke2-docs/issues/3

Remove reboot on newer versions of NetworkManager

---

docs/reference/windows_agent_config.md

Signed-off-by: Manuel Buil <mbuil@suse.com>

Add VXLAN_ADAPTER info to sync with rke2/docs

---

docusaurus.config.js

Fix config for new site

---

README.md
docs/install/requirements.md
docs/migration.md
docusaurus.config.js

Adds OS:
- Ubuntu 22.04
- SLES 15 SP4
- SLE Micro 5.3

OS Matrix bump + Readme improvements 

---

docs/install/network_options.md

Update Cilium docs with the kernel requirements.
Issue: https://github.com/rancher/rke2/issues/3571

Update Cilium requirements

---

docs/install/linux_uninstall.md
docs/security/about_hardened_images.md

- Info about SLE BCI, since we use that now
- Addresses https://github.com/rancher/rke2-docs/issues/18

Update hardened images + uninstall pages

---

docusaurus.config.js
package.json
src/theme/Navbar/MobileSidebar/Header/index.js
yarn.lock

- Address issue #23 
- Bump Docusaurus from v2.0 beta to v2.2 stable

Fix favicon + Docusaurus bump

---

docs/security/hardening_guide.md
docusaurus.config.js
package.json
yarn.lock

- We have started the process of getting Algolia search, but until that is complete, local search will cover that feature gap. 

Add local search

---

docs/security/hardening_guide.md

Signed-off-by: Brad Davidson <brad.davidson@rancher.com>

Tweak 1.25+ hardening docs

---

docs/install/linux_uninstall.md
docs/install/network_options.md
docs/security/hardening_guide.md
src/theme/MDXComponents/A.js
src/theme/MDXComponents/Code.js
src/theme/MDXComponents/Details.js
src/theme/MDXComponents/Head.js
src/theme/MDXComponents/Heading.js
src/theme/MDXComponents/Pre.js
src/theme/MDXComponents/index.js

Signed-off-by: Billy Tat <btat@suse.com>

Use global import for Tabs and TabItem

---

.github/workflows/test-deploy.yml
docs/backup_restore.md
docs/install/airgap.md
docs/install/network_options.md
docs/introduction.md
docs/networking.md
docs/security/about_hardened_images.md
docs/security/secrets_encryption.md
package.json
yarn.lock

- Adds a remark plugin for checking external links to the CI.
- Fix external dead links

External link checker + Dead link fixes

---

i18n/zh/docusaurus-plugin-content-docs/current/backup_restore.md
i18n/zh/docusaurus-plugin-content-docs/current/install/airgap.md
i18n/zh/docusaurus-plugin-content-docs/current/install/network_options.md
i18n/zh/docusaurus-plugin-content-docs/current/introduction.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/subcommands.md
i18n/zh/docusaurus-plugin-content-docs/current/security/about_hardened_images.md
i18n/zh/docusaurus-plugin-content-docs/current/security/secrets_encryption.md

Signed-off-by: vickyhella <vickyhella@hotmail.com>

Update Chinese translation

---

i18n/zh/docusaurus-plugin-content-docs/current/advanced.md
i18n/zh/docusaurus-plugin-content-docs/current/install/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/install/methods.md
i18n/zh/docusaurus-plugin-content-docs/current/install/quickstart.md
i18n/zh/docusaurus-plugin-content-docs/current/upgrade/manual_upgrade.md

Signed-off-by: kingsd041 <nicholas_ksd@hotmail.com>

Add RKE2 installation method for China

---

docs/security/pod_security_policies.md
docs/security/pod_security_standards.md
docs/security/secrets_encryption.md

Minor security doc fixes

---

docs/install/network_options.md

Updating the `network_options.md` to sync the plugins upon user click and cleaning up some markdown linting issues.

Update tag group id to help sync os

---

docs/upgrade/manual_upgrade.md

Add documentation on available channels.
* ref: https://github.com/rancher/rke2/issues/3422

Add channel info

---

docs/install/requirements.md
docs/introduction.md

- Add RHEL 9.0 to tested OS list with the completion of https://github.com/rancher/rke2/issues/3860 
- Addresses https://github.com/rancher/rke2-docs/issues/61

Add RHEL 9.0 to validation list

---

docs/install/quickstart.md
docs/install/server_roles.md
sidebars.js

Addresses: https://github.com/rancher/rke2-docs/issues/27 & https://github.com/rancher/rke2-docs/issues/39

Add server roles page + uninstall script location info

---

docs/install/network_options.md

This has been re-validated and confirmed working as part of this April release cycle.

Remove experimental flag for SRIOV

---

docs/install/quickstart.md

That wasn't clear enough, so newcomers might forget about that.

You would need to start the service in Windows Server

---

docusaurus.config.js

Fixes https://github.com/rancher/rke2-docs/issues/81.
Helps with branding/SEO per feedback from web team.

Add backlink to www.rancher.com

---

docs/install/requirements.md

Issue: https://github.com/rancher/rke2/issues/4602

Add etcd healthcheck port to requirements

---

docs/upgrade/manual_upgrade.md

Addresses: https://github.com/rancher/rke2-docs/issues/97

Add blurb about agent upgrades

---

docs/upgrade/automated_upgrade.md

Updated system-upgrade-controller to latest version and added toleration to server plan for users setting rke2-servers with the taint specified in high availability. Should close #119

latest version and toleration for servers

---

docs/security/secrets_encryption.md

- Update docs with the new `rotate-keys` command for secrets encryption.
- Use tabs for single-server and HA

Add New Secrets Encryption

---

package.json
yarn.lock

Addresses: https://github.com/rancher/rke2-docs/issues/133

Bump docusaurous to 3.0.1

---

docs/introduction.md

Reword intro

---

.github/dependabot.yml

Add dependabot updates for docusaurous

---

docs/install/methods.md

Avoids confusion as new RHEL versions are released and removes repeated instructions.

Consolidate RHEL rpm instructions

---

docs/helm.md

Addresses: https://github.com/rancher/rke2-docs/issues/158

Add section on disabling AddOn manifests

---

docs/security/token.md
sidebars.js

Document new `rke2 token rotate` subcommand.

Add page on token managment

---

docs/helm.md
docs/release-notes/v1.24.X.md
docs/release-notes/v1.25.X.md
docs/release-notes/v1.26.X.md
docs/release-notes/v1.27.X.md
docs/release-notes/v1.28.X.md
docs/release-notes/v1.29.X.md
scripts/collect-all-release-notes.sh
src/css/icon_dropdown.css

- Release notes now put newest minor on top of the sidebar
- Minor Helm note fix
- Navbar icon layout fix
**Before:**
**After:**

Order release notes with newest Minor first

---

docs/install/network_options.md

Added config file on Cilium tab with the values needed to enable Hubble.

Added config to enable hubble in cilium

---

docs/install/requirements.md

I forgot to add Windows to that line. Thanks to Mercedes Rodríguez Olmedo that caught this!

Add Flannel to supported CNIs on Windows

---

docs/install/requirements.md

Exactly the same row already exists 3 lines above.

Remove duplicate definition from firewalling table

---

.github/workflows/test-deploy.yml
docs/introduction.md

Addresses: https://github.com/rancher/rke2-docs/issues/179

Fix cncf link

---

docs/install/requirements.md

Addresses: https://github.com/rancher/rke2-docs/issues/174

Point to the SUSE support matrix for RKE2

---

docs/security/certificates.md

Addresses: https://github.com/rancher/rke2-docs/issues/175

Fix typo on rke2 service name

---

docusaurus.config.js

ref: 
* https://github.com/rancher/rke2-docs/pull/193

Fix network-options redirect typo

---

docs/install/requirements.md

Fix markdown link formatting on compatibility matrix URL

---

.github/dependabot.yml

- Should reduce the number of PRs that get open on Mondays by dependabot

Add react and remark dependabot groups

---

docs/security/hardening_guide.md

This PR does the following updates to the CIS guide:
* Reorgs `Host-level requirements` a bit. Instead of having two sections, one describing what is needed and the other one "how to configure it", I merged both and the "how to configure it" comes right after each subsection. I think it makes it more readable.
* `tigera-operator` namespace is included as exception in the section describing where restricted pod security standard is applied: https://github.com/rancher/rke2/blob/master/pkg/rke2/psa.go#L58
* Removes `kube-node-lease` namespace from the list of namespaces where the network policies are applied. We are only adding a restricted service account on that namespace: https://github.com/rancher/rke2/blob/master/pkg/rke2/serviceaccount.go#L82
* Adds more exceptions to the applied …

Update CIS guide

---

docs/advanced.md

Supersedes https://github.com/rancher/rke2-docs/pull/173

Note on volume mounts fix

---

docs/install/configuration.md
docs/install/windows_airgap.md
docs/reference/windows_agent_config.md

We forgot adding Flannel in some parts of the windows rke2-docs

Add Flannel CNI to Windows docs

---

docs/install/configuration.md
docs/install/quickstart.md
docs/install/requirements.md
docs/install/windows_airgap.md
docs/reference/windows_agent_config.md

As discussed with ProductManager and Chris, windows is not experimental anymore

Correct docs. Windows not experimental

---

docs/advanced.md
docs/backup_restore.md

- Also add a link in etcd backup around mention of configuration file (community ask).
https://github.com/rancher/rke2-docs/issues/268

Fix template link

---

docs/security/selinux.md

https://github.com/rancher/rke2-docs/issues/267

Mention requirements for AL2 selinux

---

docs/networking/networking_services.md

https://github.com/rancher/rke2-docs/issues/272

Mention the difference in service lb label for RKE2

---

docs/advanced.md

This PR updates the information which was outdated and wrong
https://github.com/rancher/rke2-docs/issues/263

Update SLES docs for NVIDIA operator

---

docs/security/hardening_guide.md

* https://github.com/rancher/rke2/issues/7655

Add note on user/group DBs

---

docs/install/private_registry.md

While trying to help an RKE2 user using privater registry, I noticed the K3s docs look better and include more information. Since the functionality is basically the same, I decided to copy parts of the private registry content of the K3s docs to RKE2.
I also moved the `rke2-runtime` version from the examples to something more updated, otherwise the docs seem to be old

Improve private registry docs

---

docs/datastore/external.md

Remove experimental support for kine
Should we add a warning about kine not being supported in clusters provisioned by rancher? I did not see references for Rancher besides the introduction.

Remove kine as experimental

---

docs/security/certificates.md

Porting k3s docs changes: https://github.com/k3s-io/docs/pull/424

Update certificate information

---

docs/install/methods.md

- We need to update the install with rpm instructions since we added a signature for the rpms

Add repo_gpgcheck for the install with rpms

---

docs/reference/server_config.md
docs/security/secrets_encryption.md

- Add info on `secretbox` and `secrets-encryption-provider` config
- Uncomment `secrets-encrypt rotate-keys` feature and bring it up to GA status.

Add information about secretbox encryption and GA rotate-keys command

---

docs/networking/basic_network_options.md

Added warning to enable route advertisement in case of IPv6.

Added warning related to the route advertisement in case of IPv6

---

docs/reference/server_config.md

Add documentation for `ingress-controller`. More about the feature here: https://github.com/rancher/rke2/issues/5928

Add ingress-controller docs

---

docs/datastore/backup_restore.md
docs/upgrades/roll-back.md

Following on from k3s etcd-snapshot PR: https://github.com/k3s-io/docs/pull/454. This PR basically copies and shows the same information for RKE2

Enhance etcd-snapshot
