rancher/rke2-docs

docs/install/network_options.md
* Add the HelmChartConfig as a comment. This is done https://docs.rke2.io/networking/#nginx-ingress-controller and I think helps a lot
* Update urls
* Use the widely used <KUBE_API_SERVER_IP> notation for the kube-proxyless cilium helmChartConfig
* Add the `cni.ChainingMode: none` when doing kube-proxyless since we will start using portmap by default (harmless if we don't do it, but let's be consistent)
* Add a couple of `bash` and move one to the left, otherwise it does not work: https://docs.rke2.io/install/network_options/#dual-stack-configuration
Signed-off-by: Manuel Buil <mbuil@suse.com>
=> Update rke2 docs

docs/install/network_options.md
There was a dualStack information that fall between the cracks and was not in sync with rke2/docs
Signed-off-by: Manuel Buil <mbuil@suse.com>
=> Sync with rke2/docs

.gitignore, docs/index.md, docs/known_issues.md, docs/reference/linux_agent_config.md, docs/reference/server_config.md, docs/reference/windows_agent_config.md, docs/security/cis_self_assessment123.md, docs/security/cis_self_assessment16.md, docs/security/hardening_guide.md, docs/security/pod_security_policies.md, docs/security/pod_security_standards.md, sidebars.js
Copy over work from https://github.com/rancher/rke2/pull/3360 into the new docs site, with minor changes to match the "docusaurus" style guides.
=> Bring RKE2 docs up to date with new CIS 1.23

docs/install/network_options.md
Adapts the current network_options file to docusarous
Now we have tabs and small windows highlighting notes and warnings!
Signed-off-by: Manuel Buil <mbuil@suse.com>
=> Adapt network_options to docusarous

docs/install/network_options.md
Removed `node-ip`  as a required option in case of dualstack.
=> Remove node-ip as a requirements on dualstack

docs/security/fips_support.md
We missed a paragraph update when coping over from the old docs as pointed out by #21 
=> Add missed sync paragraph on FIPS

.github/workflows/test-deploy.yml, docs/install/ha.md, docs/install/methods.md, docs/install/quickstart.md, docs/install/requirements.md, docs/install/windows_airgap.md, package.json, yarn.lock
Docusaurus does not validate internal links that have anchors, see https://github.com/facebook/docusaurus/issues/3321. Incorporating `remark` enables us to check for these broken links.
Example CI failure: https://github.com/rancher/rke2-docs/actions/runs/3634042128/jobs/6131725822
=> Add internal link checker

docs/backup_restore.md
"Subcommands" page link was dead, updated it to the correct one
=> Fix dead link in backup_restore.md

.github/workflows/deploy.yml
Since we use docusaraus for turning markdown to html, it is often difficult to review docs changes without the creator including screenshots, or the reviewer downloading the code change and building the website locally.
Now developers can use the workflow_dispatch function to build specific branches and deploy them to personal github pages.
Currently my `cis_workflow` is deployed to https://dereknola.github.io/docs-rke2/ using this method.
=> Add dev build workflow

docs/advanced.md
RKE2 automatically adds the cluster and service ip ranges as well as the cluster dns domain to NO_PROXY. It's not necessary to configure this manually.
This also has been documented for K3s in https://github.com/k3s-io/docs/pull/70.
See also the discussion in: https://github.com/k3s-io/docs/pull/70#discussion_r1067267161
=> Update http proxy configuration docs

docs/reference/server_config.md
In the case of "* */5 * * *", it runs every minute past every 5 hours, so it is not true that it runs every 5 hours.
To solve it set 0 as minutes (0 */5 * * *)
(may the documentation of default value is also incorrect)
=> Fix cronjob example

docs/known_issues.md
Per https://github.com/rancher/dashboard/issues/8442 we'd like to be able to link directly to this section in the dashboard.
=> Add 'Upgrading Hardened Clusters from v1.24.x to v1.25.x'  to page's table of contents

docs/install/requirements.md
Include recently validated Oracle Linux 8.7 and Rocky 9.1
=> Bump os matrix

.github/workflows/test-deploy.yml
The following warning is found in the Summary tab of each run of an action using Node.js 12. E.g. https://github.com/rancher/rke2-docs/actions/runs/5011896045.
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
=> Bump deprecated Node.js actions

docs/reference/cli_tools.md, docs/reference/logging.md
This adds documentation pages for
* List of shipped CLI tools (kubectl, ctr, crictl, etcdctl) and examples how to use them
* Locations of the various logs
Documenting this will help with debugging RKE2.
The information is taken from this excellent Gist https://gist.github.com/superseb/3b78f47989e0dbc1295486c186e944bf.
=> Add docs for shipped CLI tools and log locations

docs/install/requirements.md
Added destination column on network requirements (https://github.com/rancher/rke2/issues/4691)
=> Added destination column on networking requirements

docs/helm.md
Addresses https://github.com/rancher/rke2-docs/issues/94
=> Update helm chart values

docs/security/certificates.md, docusaurus.config.js, package.json, sidebars.js, yarn.lock
- Adds support for mermaid graphs
- Adds Certificate upkeep and manual rotation information
=> Certificates Security Page

docs/advanced.md
We need to restart `rke2-agent` to rotate certificates of agent nodes.
=> Add `rke2-agent` restart step to Certificate Rotation

docs/architecture.md
I figured this was more accurate given the current copy on the surface refers to a different ingress controller, and an easy thing to fix!
=> Update `Nginx Ingress` entry to be more accurately `Ingress-Nginx`

docs/reference/server_config.md
A parameter is specified to point to a custome admision config file : https://docs.rke2.io/security/pod_security_standards#pod-security-standards
pod-security-admission-config-file shoud be added to the server documentation
=> add pod-security-admission-config-file parameters to server configuration

docs/install/airgap.md, docs/install/methods.md, docs/install/windows_airgap.md
- Now IP used is one designated as a IPv4 testing/docs range.
- RPM repo snippets are more generic with clear support for any RKE2 minor
=> Fix Airgap Dummy IP + Use newer RKE2 versions in examples

.github/workflows/deploy.yml, .github/workflows/test-deploy.yml, docs/install/configuration.md, docs/install/ha.md, docs/release-notes/v1.25.X.md, docs/release-notes/v1.26.X.md, i18n/zh/docusaurus-plugin-content-docs/current/install/configuration.md, i18n/zh/docusaurus-plugin-content-docs/current/install/network_options.md, package.json, yarn.lock
- Bump to new Docusaurous v3, largely this change concerns going from MDXv1 to MDXv3. As such, raw <> and {} needed to be converted (usually escaped or replaced with direct html code). See [Upgrade Guide](https://docusaurus.io/docs/migration/v3) if you want more info.
=> Docusaurous v3.0.0

docs/install/airgap.md, docs/install/network_options.md, docs/install/requirements.md, docs/install/uninstall.md, docs/release-notes/v1.24.X.md, docs/release-notes/v1.25.X.md, docs/release-notes/v1.26.X.md, docs/release-notes/v1.27.X.md, docs/release-notes/v1.28.X.md, docs/security/certificates.md, docs/security/hardening_guide.md, docs/security/pod_security_policies.md, docs/security/pod_security_standards.md, docs/security/secrets_encryption.md, i18n/zh/docusaurus-plugin-content-docs/current/install/network_options.md, i18n/zh/docusaurus-plugin-content-docs/current/install/requirements.md, i18n/zh/docusaurus-plugin-content-docs/current/install/uninstall.md, i18n/zh/docusaurus-plugin-content-docs/current/security/hardening_guide.md, i18n/zh/docusaurus-plugin-content-docs/current/security/pod_security_policies.md, i18n/zh/docusaurus-plugin-content-docs/current/security/pod_security_standards.md, i18n/zh/docusaurus-plugin-content-docs/current/security/secrets_encryption.md, scripts/collect-all-release-notes.sh
With Docusaurous v3/v4 legacy admonition are being removed
The following admonitions have been migrated
- Red/Fire goes from `:::warning` to `:::danger`
- Yellow goes from `:::caution` to `:::warning`
- Blue goes from `:::important` to `:::info`
=> Admonition Migration

docs/advanced.md
- Adds missing charts that you can disable.
- Replaces list with an yaml example config to be clear how the disable flag interacts as a list, not just a single value
Addresses: https://github.com/rancher/rke2-docs/issues/123
=> Update disable charts

.github/workflows/release-notes.yml, docs/release-notes/v1.24.X.md, scripts/collect-all-release-notes.sh
- Update release notes action to only cleanup currently changing release notes (i.e. don't remove older releases notes like 1.24)
- Modify the release notes script to include a external link to the GH release page of each  patch release
- Update v1.24.X.md with new link above (all other release notes will be updated using the workflow bot)
=> Modify release notes to include link to GH release page

docs/install/requirements.md, i18n/zh/docusaurus-plugin-content-docs/current/install/requirements.md
Updated `rke2-docs` to reflect support for Amazon Linux 2023 in RKE2 PR -> https://github.com/rancher/rke2/pull/4973
* Related RKE2 Issue: https://github.com/rancher/rke2/issues/4527
* Related AL2023 Issue: https://github.com/amazonlinux/amazon-linux-2023/issues/409
=> updated docs to reflect support amazon linux 2023

docs/install/network_options.md
* `kubeProxyReplacement: strict` is now deprecated
* A couple of urls were old
* The `kubeproxy-free` cilium option is now documented on a url that does not require a version
=> Update links and new API for cilium chart kubeproxyReplacement value

docs/upgrade/automated_upgrade.md, docs/upgrade/manual_upgrade.md
Following from k3s upgrades docs, we should specify that skipping intermediate minor versions is bad.
This PR also updates some versions in the explanation so that they are more up to date
=> Warn users that upgrades should not skip intermediate minor versions

docs/install/ha.md
This information is stated in [k3s](https://docs.k3s.io/datastore/ha-embedded#existing-single-node-clusters) but not in rke2
=> Add info if etcd datastore is found in HA

docs/helm.md, i18n/zh/docusaurus-plugin-content-docs/current/helm.md
=> Removed local-storage

docs/install/network_options.md
Also remove doc about customizing the whereabouts image as it can lead to users deploying an image version not compatible with our own chart.
Related issue: https://github.com/rancher/rke2/issues/3917
=> Add doc about deploying the DHCP daemonset with Multus

docs/advanced.md, docs/security/hardening_guide.md, docs/security/pod_security_standards.md
Addresses: https://github.com/rancher/rke2-docs/issues/110
=> Add information on the generic `cis` profile

docs/reference/linux_agent_config.md, docs/reference/server_config.md, scripts/help_to_markdown.py
Address Issue: https://github.com/rancher/rke2-docs/issues/142
=> Move to a script generated markdown table for RKE2 server and agent help

docs/security/secrets_encryption.md
The `secrets-encrypt rotate-keys` command has proven to be to unstable with upstream changing how KMSv2 works. Removing information from docs until the command is GA.
=> Hide new rotate-keys command until stable

docs/install/network_options.md, docs/install/requirements.md
=> Add Flannel CNI docs

.github/workflows/deploy.yml
Moves away from third party actions to using Actions from GitHub. Requires configuration through the GitHub UI to complete the setup process.
Tested as working at: https://dereknola.github.io/docs-rke2/
=> Switch to github native actions for gh-pages

docs/install/network_options.md
Support org just warned me that we are not specifying that Flannel is still experimental
=> Flannel is experimental

docs/install/quickstart.md
Adds information required for flannel
=> Add the HNS networking component

docs/install/quickstart.md
I made a mistake and got confused by something else. The containers feature is enough to get all windows requirements in place
=> Remove the hyper-v feature as it is not needed in the end

docs/security/cis_self_assessment123.md
This PR will fix incorrect file extensions mentioned in the documentation (tested against v1.26.13+rke2r1).
=> docs: fix incorrect file extension

docs/advanced.md
Adds information about how to deploy the NVIDIA operator
=> Add docs explaining how to deploy the NVIDIA operator

docs/advanced.md
Removing the term "experimental" from our NVIDIA docs
Issue: #216
=> Remove experimental from GPU deployment docs

docs/networking/basic_network_options.md
This PR adds information about how to enable the kernel checksum calculation offloading mechanism which improves TCP performance from 2.5Gbps to 9Gbps
=> Add calico config to enable the kernel checksum offloading

docs/security/selinux.md
After installing the required packages, he noticed that the canal & coredns installation failed at some point: 
```console
NAME            STATUS     ROLES                       AGE    VERSION
mgxrk8sinf339   NotReady   control-plane,etcd,master   120m   v1.27.10+rke2r1
NAMESPACE     NAME                                                  READY   STATUS              RESTARTS      AGE
kube-system   cloud-controller-manager-mgxrk8sinf339                1/1     Running             0             40s
kube-system   etcd-mgxrk8sinf339                                    1/1     Running             0             16s
kube-system   helm-install-rke2-canal-r4rgk                         0/1     RunContainerError   2 (13s ago)   35s
kube-system   helm-install-rke2-coredns-d9c4c                       0/1 …
```
=> Update selinux.md to add a note on a possible required reboot for CentOS/RHEL systems

docs/networking/networking_services.md
Related rke2 PR: https://github.com/rancher/rke2/pull/6372
=> Add doc on using Local Direct Policy for coredns when using Cilium in kp replacement mode

docs/install/requirements.md, docs/networking/basic_network_options.md, docs/security/secrets_encryption.md
Break out the list of Networking Rules into General RKE2 ports and CNI specific tables (with querystring support so you can link to each table specifically)
=> Seperate Network Rules into different CNI tables

docs/upgrade/automated_upgrade.md
Addresses: https://github.com/rancher/rke2-docs/issues/222
=> Mention CRD install for system-upgrade-controller

docs/backup_restore.md
- After recent triage, clarify that to manually prune scheduled snapshots, you need to give the `--name etcd-snapshot`
=> Add note how to prune scheduled snapshots

.github/workflows/release-notes.yml, docs/release-notes/v1.24.X.md, docs/release-notes/v1.25.X.md, docs/release-notes/v1.26.X.md, docs/release-notes/v1.27.X.md, docs/release-notes/v1.28.X.md, docs/release-notes/v1.29.X.md, docs/release-notes/v1.30.X.md, docs/release-notes/v1.31.X.md, package.json, scripts/collect-all-release-notes.sh, yarn.lock
- Bump docusaurus/theme-common, dependabot seems to skip this for some reason
- Have the release notes script run every week (if no diff, no PR is opened)
=> Add v1.31 release notes page

docs/security/cis_self_assessment123.md, docs/security/cis_self_assessment124.md, docs/security/cis_self_assessment17.md, docs/security/cis_self_assessment18.md, docs/security/hardening_guide.md, scripts/kubebench-to-markdown.sh, sidebars.js
Adds the newest CIS scans available in Rancher:
- CIS 1.24
-  CIS 1.7
-  CIS 1.8
Adds kube-bench to markdown script (for use with overhauled security-scan profiles)
Remove cis 1.23 and older guides from side bar (still accessible via direct url)
=> Overhaul CIS scan documentation

docs/install/requirements.md
Addresses: https://github.com/rancher/rke2-docs/issues/255
Note: the 1.31 page is currently broken as the link appends a `//` at the end, resulting in a 404.
=> Fix RKE2 suppport matrix link

docs/advanced.md
This change:
1 - Mentions the existence of open drivers and how to install them
2 - Updates the URL of the repo for proprietary NVIDIA drivers for SLES
3 - Updates the ubuntu package version
=> Update NVIDIA-rke2 docs

.github/workflows/release-notes.yml
Tested on my fork https://github.com/dereknola/docs-rke2/actions/runs/11670237499 which opened https://github.com/dereknola/docs-rke2/pull/3
=> Replace dedicated action pull request with gh/git commands

yarn.lock
https://github.com/rancher/rke2-docs/pull/282 Missed the bump necessary to the `yarn.lock` file for the `theme-common` dependency bump.
=> Add theme-common bump to yarn.lock file

docs/advanced.md, docs/datastore/backup_restore.md, docs/install/airgap.md, docs/install/configuration.md, docs/install/containerd_registry_configuration.md, docs/install/quickstart.md, docs/install/windows_airgap.md, docs/known_issues.md, docs/networking/multus_sriov.md, docs/security/fips_support.md
Remove information about 1.19, 1.20 and 1.21 kubernetes versions as they are super old.
Update backup/restore info on the "Restoring a Snapshot to New Nodes" section (token was missing)
=> Remove 1.19, 1.20 and 1.21 warnings and update backup/restore

docs/install/requirements.md
Adding requirement for cilium + wireguard setup.
This port is documented in [cilium doc](https://docs.cilium.io/en/stable/security/network/encryption-wireguard/#encryption-wg)
=> document cilium requirement when enabling wireguard

.github/workflows/test-deploy.yml
Remove the "opened" filter to force CI to run the check in each sync on the PR
=> Remove types opened for the test workflow

.codespellrc, .github/workflows/codespell.yml, docs/install/windows_airgap.md, docs/reference/linux_agent_config.md, docs/reference/server_config.md, docs/security/fips_support.md, docs/security/hardening_guide.md, docs/security/secrets_encryption.md, i18n/zh/docusaurus-plugin-content-docs/current/install/windows_airgap.md
Copied over the codespell action we are running in k3s docs
=> Add codespell action

docs/install/quickstart.md, docs/install/requirements.md, docs/install/windows_airgap.md, i18n/zh/docusaurus-plugin-content-docs/current/install/quickstart.md, i18n/zh/docusaurus-plugin-content-docs/current/install/requirements.md, i18n/zh/docusaurus-plugin-content-docs/current/install/windows_airgap.md
Fixing an encoding issue when copy/paste is performed from the documentation.
```
A positional parameter cannot be found that accepts argument '\xe2\x80\x93All'.\
```
=> Fix weird encoding issue with -All option

docs/networking/networking_services.md
I was trying to install some LB on my baremetal deployment when I learnt about `serviceLb`
The correct command seems to be `--enable-servicelb`. Updated that in the docs.
=> Change serviceLb to enable-servicelb

docs/install/private_registry.md
Add instruction on how to apply a rewrite when pulling directly from a registry, that is not being used as a mirror for a different upstream registry. Copied from k3s docs at https://docs.k3s.io/installation/private-registry#rewrites
=> Add docs for rewrite when pulling directly from registry

docs/advanced.md, docs/install/ha.md, docs/install/registry_mirror.md
Some confusion over how to properly configure Spegel in rancher prompted a second pass over these docs.
- Remove references to flag configs (ie `--flag`). Thats not how 99% of people control RKE2.
- Move Metrics up the page and put it as a subsection just after "Enabling". Hopefully people will see this sooner and know that they want
```
embedded-registry: true
supervisor-metrics: true
```
Right from the start, instead of having them realize it later and need to restart all their clusters.
=> Cleanup instructions for Spegel, remove flag references.

docs/security/token.md
The token management tool is in both K3s and RKE2, however, the docs in RKE2 are minimal, whereas the K3s docs about it are good and cover all the different options. This PR basically copies K3s information, replacing K3s specifics with RKE2
=> Add extra info about token management tool

docs/networking/basic_network_options.md, docs/networking/multus_sriov.md
Modify the RKE2 CNI docs based on feedback from a confused user in https://github.com/rancher/rke2-docs/issues/323
Mention the `cni` config file key more prominently, and make it more explicit how charts are bundled. Also drop references to CLI flags, since we are standardizing on only referencing the config file in docs.
=> CNI chart docs tweaks

docs/install/requirements.md
Nothing in the docs was mentioning the CPU architectures we support
=> Add architecture in the installation requirements

docs/datastore/backup_restore.md
Add call-out on the correct value for --cluster-reset-restore-path when an etcd-s3 backup configuration is present in the RKE2 config file, and how to correctly restore from a local snapshot file in that case.
=> Add note on restores where etcd-s3 config is present

docs/security/hardening_guide.md
I think it is useful to add the applied etcd configuration when RKE2 is configured with `profile: cis`. It was mentioned above but it could be easily missed
=> Add etcd step done when profile: cis

docs/advanced.md
This PR:
*  removes the host OS driver installation section and considers that as out of the scope. This part changes very often and is very error prone. Moreover, RKE2 should not be in charge of this.
* Adds three commands that the user should run to verify that the host OS is correctly configured
* Adds an extra verification step after deploying the NVIDIA operator to check that the operator detected the nvidia drivers
* Small modification of the `NVIDIA_DRIVER_CAPABILITIES` value: apply principle of least privilege
=> Update NVIDIA GPU docs. Removing the OS part

docs/upgrades/automated_upgrade.md
Add comments to the example agent upgrade Plan manifest. The comments indicate that part of the example filter is optional and will exclude some nodes, mirroring explanatory notes below the example, and instruct users to delete them to include all agent nodes in the plan.
I also moved that example to the end of the list, to hopefully avoid accidentally deleting the selector that excludes server nodes.
Related to https://github.com/rancher/system-upgrade-controller/issues/217
=> Add comments to example upgrade manifest

docs/security/certificates.md, docs/security/hardening_guide.md
Add missing information about the "rke2 certificate expiration" command in the docs. Same as in K3s. 
It also fixes a stupid typo I added in a previous PR
=> Add information about the expiration date of certificates

docs/networking/basic_network_options.md, i18n/zh/docusaurus-plugin-content-docs/current/networking/basic_network_options.md
Users have been running Windows and Flannel for more than a year and QA is rigorously testing it, so we can consider it stable
=> Remove Windows-Flannel experimental

docs/security/selinux.md
Update SELinux support note to cover RHEL/CentOS 7+
=> Make SELinux compatibility future-proof

docs/networking/basic_network_options.md
Added a configuration to use in Cilium in case of IPv6 only setup where the pods traffic is not tunneled and requires specific route on the node.
=> Added IPv6 only Cilium config

docs/install/airgap.md, docs/install/registry_mirror.md
Even though most of the code is shared, the K3s/RKE2 docs are not that similar.
This PR tries to make k3s/rke2 more similar (same subtitles, titles, organization...)
=> Sync docs with K3s on airgap

.github/workflows/asciidoc.yml
Added a github action that automatically updates the `main-ascii` branch with any new documentation changes from the `main` branch.
See https://github.com/dereknola/docs-rke2/commits/main-ascii/ for an example on my personal fork.
=> Add automatic GHA conversion of markdown to asciidoc

docs/install/requirements.md
The table says ports 6443 & 9345 need to be open to just agent nodes, but my firewall logs show that the server (controlplane) nodes also need to reach these ports on their fellow controlplane nodes.
Also, this sentence above suggests that the ports need to be open to all nodes:
> The RKE2 server needs port 6443 and 9345 to be accessible by other nodes in the cluster.
When provisioning a downstream cluster, I only opened these ports to the agent nodes. My contolplane nodes are named cp01, cp02, cp03 with IPs ending in 101, 102, 103. cp02 was selected as the 'bootstrap' node. The other two controlplane nodes could not join because their connections were being blocked by the firewall. Here are some abbreviated logs.
```
2025-07-28T14:24:30 cp02 kernel: DROP-INPUT: IN=ens192 OUT= …
```
=> Ports 6443 & 9345 must be open from all nodes, not just agent nodes

docs/advanced.md
Apparently we've always done this 🤷🏻 
https://github.com/rancher/rke2/blame/a9a0c194cbd38117b034ddd09ff7a4da0c8efe46/pkg/staticpod/staticpod.go#L273-L277
=> Mention that proxy vars are passed to managed pods

docs/networking/basic_network_options.md
* Add wireguard config for Cilium
* Use wireguard config as example for Cilium as it is more widely used than the "eni" config
* Create two drop-down menus, so that only users that require kube-proxyless solution or hubble see the information
=> Add wireguard option for Cilium

docusaurus.config.js
Reverts rancher/rke2-docs#399
Per community analytics slack discussion, use GTM script generated by: 
```
googleTagManager: {
containerId: 'GTM-XXXXXXX',
},
```
=> Revert "Add global site tag for Google Analytics"

.github/workflows/asciidoc.yml, .github/workflows/browserlist.yml, .github/workflows/deploy.yml, .github/workflows/release-notes.yml, .github/workflows/test-deploy.yml, docs/release-notes-old/v1.24.X.md, docs/release-notes-old/v1.25.X.md, docs/release-notes-old/v1.26.X.md, docs/release-notes-old/v1.27.X.md, docs/release-notes-old/v1.28.X.md, docs/release-notes-old/v1.29.X.md, docs/release-notes/v1.30.X.md, docs/release-notes/v1.31.X.md, docs/release-notes/v1.32.X.md, docs/release-notes/v1.33.X.md, docs/release-notes/v1.34.X.md, scripts/collect-all-release-notes.sh
- Remove browserlist update from collect release notes, run as independent cron job 
- Bump setup-node to v5, ensure node 22+ is used
- Move v1.29 to older release notes section
=> Add v1.34 release notes page

docusaurus.config.js, static/scripts/optanonwrapper.js
Requested by SD-192521. 
> Since we have Google Analytics on the domain, it is necessary to implement OneTrust to ensure compliance.
=> Add OneTrust to ensure compliance
